/*  
 * A little script to compile the version information.
 * Run as `node versioninfo.js > src/environments/versioninfo.ts`
 */

const { execSync } = require('child_process');
const package = require('./package.json');

let template = `
/**
 *  NOTICE: This file is generated by versioninfo.js and not version controlled.
 */

export class VersionInfo {
    static version = '<VERSION>';
    static build = '<BUILD>';
    static date = '<DATE>';
}
`;

let version = package.version;
let build = execSync('git describe --tags --always --dirty');


let result = template.replace('<VERSION>', version.trim());
result = result.replace('<BUILD>', build.toString().trim());
result = result.replace('<DATE>', new Date().toISOString());

console.log(result);
